### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by chenpaner** [ryjacky/PieMenyu#12]
1. Can  add pure black and pure white to the color settings? Of course, it would be best if can customize color.
2. Why does the font color not affect the text color of the activated item?
![image](https://github.com/ryjacky/PieMenyu/assets/107256886/c31bba66-f4fb-4ba9-b211-0082762b043a)

3. Can`t change send text when editting,but actually it works
![can not change text](https://github.com/ryjacky/PieMenyu/assets/107256886/1832f9c9-264f-41c6-84d8-f2912fa4f19e)

4.Can  use mouse buttons as Pie`s shortcut keys?
![image](https://github.com/ryjacky/PieMenyu/assets/107256886/fb0517b5-f85e-4bbd-889c-e3f113eeb48b)

**Comment by ryjacky** [comment]
Thanks for the questions!

1. You're right, I didn't use a color picker just because this UI looks good to me lol, but I would try to add a color picker in the next version.
2. The font color does not affect the active item because it uses the secondary color (background color) by default, I do it this way because that when you set primary color and font color to white (for example), the text will be invisible on active item, let me know if you have better solution to this.
3. Let me confirm one thing, it correctly sends 1 and 2 when activated but the UI didn't update right?
4. Yes, PieMenyu doesn't support that directly but if your mouse is programmable, you can assign a shortcut like Ctrl+alt+shift+k to both the PieMenyu and the mouse button.

---
Since you're in the editor page and if you didn't know already, you could drag and drop the slices to reorder them (Sry I need some time to include all the instructions into the app itself)

**Comment by chenpaner** [comment]
3. Yes, just UI didn't update
